store.key=powerzona
app.key=powerzona-storefront-staging
store.url=https://tusenda84.com/t/powerzona
app.display_name=PowerZona
application.id=com.tusenda84.powerzona
brand.key=powerzona
version.code=6
version.name=0.2.4
